default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: component
  
test:  
  <<: *default
  database: componenttest
